---
rss: 
  homeable: false
  required: false
  tables: 
    rss_modules: |
      
      rss_id I4 AUTO PRIMARY,
      name C(30) NOTNULL,
      description X,
      url C(255) NOTNULL,
      refresh I4,
      last_updated I8,
      show_title C(1) DEFAULT 'n',
      show_pub_date C(1) DEFAULT 'n',
      content X
      
    rss_feeds: |
      
      name C(30) NOTNULL,
      rss_ver C(1) NOTNULL DEFAULT '1',
      refresh I4 DEFAULT '300',
      last_updated I8,
      rss_cache B
      
  preferences: 
    rssfeed_cache_time: 3600
    boards_rss: y
    portfolio_rss: y
    blogs_rss: y
    fisheye_rss: y
    treasury_rss: y
    wiki_rss: y
  version: 0.0.0
  description: >
    Resource Description Framework (RDF)
    Site Summary (RSS) is a lightweight
    multipurpose extensible metadata
    description and syndication format. It
    allows users to read healines from your
    site with a dedicated RSS reader.
  license: 
    html: '<a href="http://www.gnu.org/licenses/licenses.html#LGPL">LGPL</a>'
